name: Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Execute
        run: sh src/gitlab_status.sh
      - name: Check up
        if: ${{ env.GITLAB_STATUS  == 'up' }}
        run: echo "gitlab is up"
      - name: Check down
        if: ${{ env.GITLAB_STATUS  == 'down' }}
        run: echo "gitlab is down"
