name: Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install curl
        run: sudo apt-get install -y curl
      - name: Execute
        env:
          GITHUB_ENV: ${{ env.GITHUB_ENV }}
        run: sh ./src/gitlab_status.sh
      - name: Check up
        if: ${{ env.GITLAB_STATUS  == 'up' }}
        run: echo "gitlab is up"
      - name: Check down
        if: ${{ env.GITLAB_STATUS  == 'down' }}
        run: echo "gitlab is down"
      - name: AND condition
        if: ${{ secrets.FOOBAR == 'true' && env.GITLAB_STATUS  == 'up' }}
        run: echo "lorem ipsum ${{ secrets.FOOBAZ }}"
