name: Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check existence of FOOBAR
        env:
          FOOBAR: ${{ secrets.FOOBAR }}
        if: ${{ env.FOOBAR != 0 }}
        run: echo 'FOOBAR env exists'
      - name: Check existence of ABC
        env:
          ABC: ${{ secrets.ABC }}
        if: ${{ env.ABC == 0 }}
        run: echo 'ABC does not exist'
